### ISSUE TITLE
/bin/sh: ./jasperstarter: not found 

### ISSUE THREAD

**Issue by komgrip** [PHPJasper/phpjasper#291]
I've had the problem with jasperstarter on linux server
the debug :
`./jasperstarter process "./jasper_test.jrxml" -o "./pdf" -f pdf -P p_value="test" -t mysql -u test -p 123456789 -H 192.168.0.101 -n test `
Error :
`/bin/sh: ./jasperstarter: not found` 

if I remove `./` in front of `./jasperstarter`, in line 87 it's work
I'd like to know why the phpjasper library have to add `./`

<img width="1013" alt="Screen Shot 2564-06-25 at 12 35 39" src="https://user-images.githubusercontent.com/84488643/123375285-b4d9ce00-d5b2-11eb-8ca8-5b87504b9e49.png">

thank you.

**Comment by mfrieling** [comment]
I'm not sure, but I guess when using the binary name without the `./` Linux searching for it in all directories listed in the `PATH` environment variable only. So you need to add the `./` to tell Linux to use the binary/executable in the current directory, which is resolved in the constructor as the _"path of the `PHPJasper` class"_ `. '/../bin/jasperstarter/bin`.

There is a second problem:
It changes the current working directory to the path containing the `jasperstarter` binary just before it's execution to be able to call it this way. Better would be to not change the working directory and instead prepend the path and execute the binary with its absolute path instead. The problem arises as the current working directory is not restored to what is was just before changing it, which can break any other PHP code executed by the callee afterwards. This works on Linux and should work on Windows as well, but I can't test it.

**Comment by mfrieling** [comment]
Attached is a git patch which changes the current working directory back directly after execution. I will create a pull request when I've updated the tests accordingly, but upload the patch here to enable users to apply it via [cweagans/composer-patches](https://github.com/cweagans/composer-patches).

[change-cwd-back-291.txt](https://github.com/PHPJasper/phpjasper/files/6808347/change-cwd-back-291.txt)
(I have to use the file extenion `.txt` because GitHub doesn't support uploading `.patch` files.)
