### ISSUE TITLE
Argument -p: expected one argument

### ISSUE THREAD

**Issue by amelyec** [PHPJasper/phpjasper#63]
Facing the error below while trying to compile;

D:\xampp\htdocs\pro\testoneusage: jasperstarter process [-h] -f <fmt> [<fmt> ...] [-o <output>] [-w]
                     [-a [<filter>]] [-P <param> [<param> ...]]
                     [-r [<resource>]] [-t <dstype>] [-H <dbhost>]
                     [-u <dbuser>] [-p <dbpasswd>] [-n <dbname>]
                     [--db-sid <sid>] [--db-port <port>]
                     [--db-driver <name>] [--db-url <jdbcUrl>]
                     [--jdbc-dir <dir>] [--data-file <file>]
                     [--csv-first-row] [--csv-columns <list>]
                     [--csv-record-del <delimiter>]
                     [--csv-field-del <delimiter>]
                     [--csv-charset <charset>] [--xml-xpath <xpath>]
                     [--json-query <jsonquery>] [-N <printername>] [-d]
                     [-s <reportname>] [-c <copies>]
                     [--out-field-del <delimiter>]
                     [--out-charset <charset>] <input>
jasperstarter: error: argument -p: expected one argument
PHP Fatal error:  Uncaught exception 'JasperPHP\Exception\ErrorCommandExecutable' with message 'Your report has an error and couldn 't be processed!\ Try to output the command using the functi
on `output();` and run it manually in the console.' in D:\xampp\htdocs\pro\testone\vendor\geekcom\phpjasper\src\JasperPHP.php:198
Stack trace:
#0 D:\xampp\htdocs\pro\testone\report.php(52): JasperPHP\JasperPHP->execute()
#1 {main}
  thrown in D:\xampp\htdocs\pro\testone\vendor\geekcom\phpjasper\src\JasperPHP.php on line 198

Fatal error: Uncaught exception 'JasperPHP\Exception\ErrorCommandExecutable' with message 'Your report has an error and couldn 't be processed!\ Try to output the command using the function `o
utput();` and run it manually in the console.' in D:\xampp\htdocs\pro\testone\vendor\geekcom\phpjasper\src\JasperPHP.php:198
Stack trace:
#0 D:\xampp\htdocs\pro\testone\report.php(52): JasperPHP\JasperPHP->execute()
#1 {main}
  thrown in D:\xampp\htdocs\pro\testone\vendor\geekcom\phpjasper\src\JasperPHP.php on line 198

**Comment by geekcom** [comment]
Hello @amechax, show your code.

**Comment by amelyec** [comment]
Hi, please find the code below

    require __DIR__ . '/vendor/autoload.php';

    use JasperPHP\JasperPHP;

    $input = __DIR__ . '/vendor/geekcom/phpjasper/examples/TemplateData03.jrxml';   
    echo __DIR__;

    $jasper = new JasperPHP;
    $jasper->compile($input)->execute();

    $input = __DIR__ . '/vendor/geekcom/phpjasper/examples/TemplateData03.jasper';  
    $output = __DIR__ . '/vendor/geekcom/phpjasper/examples';    

    $options = [
        'format' => ['pdf'],
        'locale' => 'en',
        'params' => [],
        'db_connection' => [
        'driver' => 'mysql',
        'username' => 'root',
        'password' => '',
        'host' => 'localhost',
        'database' => 'crm',
        'port' => '3306'
        ]
    ];

    $jasper->process(
            $input,
            $output,
            $options
    )->execute();

**Comment by azaman2204** [comment]
How I solved/figured out with this ERROR below: 

> Fatal error: Uncaught exception 'JasperPHP\Exception\ErrorCommandExecutable' with message 'Your report has an error and couldn 't be processed!\ Try to output the command using the function o utput(); and run it manually in the console.
 
1.  As suggested by geekcom, I echo the output commands to execute by changing the following to get the command line

`$jasper->process(
        $input,
        $output,
        $options
)->execute();`
 TO
` echo  $jasper->process(
        $input,
        $output,
        $options
)->output();`

2. I ran the output of the above (1) on the console, and found out the issue/problem.
Found out the problem was with one of my parameter that was using  **java.sql.Date**  type which is not yet supported by PHPJasper. I changed the parameter type in Jasper Studio to   **string** type and it solved the problem.

**Comment by geekcom** [comment]
Great.

XD
________________________________
De: azaman2204 <notifications@github.com>
Enviado: quinta-feira, 23 de novembro de 2017 21:31
Para: PHPJasper/phpjasper
Cc: Daniel Rodrigues; Comment
Assunto: Re: [PHPJasper/phpjasper] Argument -p: expected one argument (#63)


How I solved/figured out with this ERROR below:

Fatal error: Uncaught exception 'JasperPHP\Exception\ErrorCommandExecutable' with message 'Your report has an error and couldn 't be processed!\ Try to output the command using the function o utput(); and run it manually in the console.

  1.  As suggested by geekcom, I echo the output commands to execute by changing the following to get the command line

$jasper->process( $input, $output, $options )->execute();
TO
echo $jasper->process( $input, $output, $options )->output();

  1.  I ran the out of the above (1) on the console, and found out the issue/problem.
Found out the problem was with one of my parameter that was usinag java.sql.Date tyep which is not yet supported by PHPJasper. I changed the paramter type in Jasper Studio to string type and it solved the problem.

**Comment by mutaqinzae** [comment]
> 
> 
> How I solved/figured out with this ERROR below:
> 
> > Fatal error: Uncaught exception 'JasperPHP\Exception\ErrorCommandExecutable' with message 'Your report has an error and couldn 't be processed!\ Try to output the command using the function o utput(); and run it manually in the console.
> 
>     1. As suggested by geekcom, I echo the output commands to execute by changing the following to get the command line
> 
> 
> `$jasper->process( $input, $output, $options )->execute();`
> TO
> ` echo $jasper->process( $input, $output, $options )->output();`
> 
>     1. I ran the output of the above (1) on the console, and found out the issue/problem.
>        Found out the problem was with one of my parameter that was using  **java.sql.Date**  type which is not yet supported by PHPJasper. I changed the parameter type in Jasper Studio to   **string** type and it solved the problem.

Dear @azaman2204 

How to run the output from console? 
Thanks in advance

Regards,
Zaenal M

**Comment by akhil5570** [comment]
Dear @amechax   ,  Argument -p: expected one argument  | Because you not passed any password in the DB config. Create an user for your database and assign rights, then pass that username and password in Jasper config.
