### ISSUE TITLE
Support to Collections

### ISSUE THREAD

**Issue by flavioribeirojr** [PHPJasper/phpjasper#64]
I don't know if is lack of my knowledge, but i can't discover how to pass parameters that in my report are of the Collection type. Do your library support it?

**Comment by geekcom** [comment]
Hi @flavio-jr,

Parameters can be used in SQL queries to filter records in a where condition or to add/replace pieces of raw SQL or even to pass the entire SQL string to execute.
In the first case the parameters are used as standard SQL parameters, in example:

`SELECT * FROM ORDERS WHERE ORDER_ID = $P{my_order_id}`

In this example my_order_id is a parameter that contains the ID of the order to read. This parameter can be passed to the report from the application that is running it to select only a specific order. Please note that the parameter here is a real SQL parameter, meaning that the query will be executed using a prepared statement like:

`SELECT * FROM ORDERS WHERE ORDER_ID = ?`
 
Please read this article:
https://community.jaspersoft.com/wiki/using-report-parameters

**Comment by flavioribeirojr** [comment]
I want to use a WHERE IN statement in my SQL, so i'm passing many ids to my report. In iReport they use a Collection parameter to filter the registers. I just want to know if is possible to pass such parameter type from PHP to Jasper

**Comment by flavioribeirojr** [comment]
Here is my workaround: I'm passing a string parameter, and in the report I make a "split" to get an array.

**Comment by rafaelqueiroz** [comment]
@flavio-jr you can provide me a sample of your report ?

**Comment by miltonisaya** [comment]
[PE8b.zip](https://github.com/PHPJasper/phpjasper/files/1531460/PE8b.zip)
Provided is the .jrxml file I am working on. I want to pass my parameters using your library. I keep on getting the array to string conversion error. Please assist

**Comment by tantanito** [comment]
@flavio-jr Do you have a working example? Can't get to work with collections.

**Comment by hemimm** [comment]
When I put a parameters we have a Fatal error: Uncaught  PHPJasper\Exception\ErrorCommandExecutable: your report has an error couldn´t be processed.

I did in JasperSoft Studio: Select * from table Where field between P{field_start} and P{field_end}

In PHPJasper:
require __DIR__.DIRECTORY_SEPARATOR.'vendor'.DIRECTORY_SEPARATOR.'autoload.php';
use PHPJasper\PHPJasper as PHPJasper;

$file = 'DataMatrix.jasper';
$fieldstart = 'CA1234';
$fieldend = 'CA5678';

$input = __DIR__.DIRECTORY_SEPARATOR.$file;
$output = __DIR__;
$options => [
  'format' => ['pdf'],
  'locale' => 'en'
  'params => [
     'field_start' => $fieldstart,
     'field_end' => $fieldend
   ],
  'dbconnection => [
     'driver' => 'mysql',
     'username' => 'root',
     'password' => 'password',
     'host' => 'localhost:8080',
     'database' => 'database',
     'port' => '3306'
]
$jasper = new PHPJasper;
$jasper -> process($input,$output,$options)->execute();

Without parameters result a blank report, With partameters result the error. 

I couldn´t find out the error. I thank for help, and sorry for my bad english.

**Comment by geekcom** [comment]
Hi @hemimm please check your .jrxml report,
parameters should be used in this way:

`$P{my_order_id}`

**Comment by hemimm** [comment]
As my english is not good, I will add information in portuguese.

Para ver as informações passadas, coloque $jasper->process($input,$output,$options)->output e obtive
Jasper starter --locale em process "D:\web\DataMatrix.jasper" -o "D:\web" -f pdf -P  field_start = "CA1234" field_end "CA5678" -t mysql -u root -p password -H localhost:8080 -n database --d-port 3306

Espero que com isto ajude a solucionar o problema.

**Comment by hemimm** [comment]
Yes, it  is in this way.

**Comment by hemimm** [comment]
In JasperSoft Studio, the report is normal, but not in PHPJasper

**Comment by hemimm** [comment]
the complete error:

Fatal error: Uncaught PHPJasper\Exception\ErrorCommandExecutable: Your report has an error and couldn 't be processed!\ Try to output the command using the function `output();` and run it manually in the console. in D:\web\vendor\geekcom\phpjasper\src\PHPJasper.php:219 Stack trace: #0 D:\web\RotulosdaEtiquetasPHPJasper.php(157): PHPJasper\PHPJasper->execute() #1 {main} thrown in D:\web\vendor\geekcom\phpjasper\src\PHPJasper.php on line 219

**Comment by hemimm** [comment]
line 157  is $jasper($input,$output,$options)->execute()

**Comment by hemimm** [comment]
Yes, it is in this way. In deed in JasperSoft Studio the report is normal, but not in PHPJasper

Enviado do Email<https://go.microsoft.com/fwlink/?LinkId=550986> para Windows 10

________________________________
De: Daniel Rodrigues <notifications@github.com>
Enviado: Thursday, May 3, 2018 9:37:49 AM
Para: PHPJasper/phpjasper
Cc: hemimm; Mention
Assunto: Re: [PHPJasper/phpjasper] Support to Collections (#64)


Hi @hemimm<https://github.com/hemimm> please check your .jrxml report,
parameters should be used in this way:

$P{my_order_id}

**Comment by hemimm** [comment]
Daniel bom dia! (Daniel good morning!)

Como disse ele já está desta forma.

Não sei se isto ajuda, mas o .jrxml tem 2 código de barras e  1 datamatrix do Barcode  e 3 imagens, todos do Basic Elements do JasperSoft Studio. Podem estar interferindo, se estiverem não sei como interagir com o PHPJasper.

O Relatório está em formato de etiquetas, com 4 etiquetas / página.


As I told you before my .jrxml is aready in this way  $P{parameter}
I do not know if this help you, but my .jrxml has 2 bar code and 1 datamatrix from Barcode and 3 images, all from Basic Elements´s JasperSoft Studio. They could be interfering, if they were I do not know how to Interact with PHPJasper.

My Report is in label format, with 4 label / page.

At.

Enviado do Email<https://go.microsoft.com/fwlink/?LinkId=550986> para Windows 10

________________________________
De: Daniel Rodrigues <notifications@github.com>
Enviado: Thursday, May 3, 2018 9:37:49 AM
Para: PHPJasper/phpjasper
Cc: hemimm; Mention
Assunto: Re: [PHPJasper/phpjasper] Support to Collections (#64)


Hi @hemimm<https://github.com/hemimm> please check your .jrxml report,
parameters should be used in this way:

$P{my_order_id}

**Comment by hemimm** [comment]
Se o PhpJasper não é capaz de gerar este tipo de relatório, irei procurar outro tipo de gerador de pdf. Mas antes gostaria que se pronunciassem a respeito.
At.

**Comment by hemimm** [comment]
Vamos encerrar a solicitação, considerando como NÃO RESOLVIDO. Se eu achar uma solução postarei para vocês. At.

**Comment by geekcom** [comment]
@hemimm PHPJasper é capaz de resolver sua demanda, acredito que exista algum problema de configuração aí, por favor verifique o manual com atenção.

**Comment by hemimm** [comment]
Daniel boa tarde!

Estou estudando os campos colocados no JasperSoft, até o momento verifiquei os seguintes:

O jrxml no PHP não está aceitando um IF que normalmente é aceito no JasperSoft:
Ex.  $F{DESTEND}==null?"":$F{DESTEND}.trim()+","+$F{DESTNUM}

Não aceita também a função trim() e também a concatenação dos campos.

Neste momento estou verificando a interferência das imagens, que também não estão saindo no Relatório.

O próximo passo é verificar por que as etiquetas só saem em uma coluna e não em duas, conforme está no projeto e no JasperSoft funciona normalmente.

Manterei informado. Como auxílio gostaria que elucidasse de como analisar as configurações do PHPJasper, que na realidade não sei nem por onde começar.

At.

Enviado do Email<https://go.microsoft.com/fwlink/?LinkId=550986> para Windows 10

________________________________
De: Daniel Rodrigues <notifications@github.com>
Enviado: Wednesday, May 9, 2018 11:29:24 AM
Para: PHPJasper/phpjasper
Cc: hemimm; Mention
Assunto: Re: [PHPJasper/phpjasper] Support to Collections (#64)


@hemimm<https://github.com/hemimm> PHPJasper é capaz de resolver sua demanda, acredito que exista algum problema de configuração aí, por favor verifique o manual com atenção.

**Comment by geekcom** [comment]
Olá @hemimm, dê uma olhada no repositório de exemplos e estude um pouco mais de PHP, percebo que o problema não está na biblioteca.

Take a look at the examples repository and study a little more of PHP, I realize that the problem is not in the library

**Comment by hemimm** [comment]
Daniel bom dia!

Não consegui visualizar onde está ocorrendo o problema no arquivo gerado pelo JasperSoftStudio para não ser compatível como PHPJasper.

Mas resolvi o problema com o MPdf e o Zint, que geram as etiquetas com imagem e datamatrix. As etiquetas geradas podem ter 2 ou mais colunas, 2 ou mais fileiras de etiquetas. Umas das vantagens é que ambos são compatíveis a partir da versão PHP5.

O MPdf é instalado através do Composer e o Zint com simples download.

At. Mitugi

Enviado do Email<https://go.microsoft.com/fwlink/?LinkId=550986> para Windows 10

________________________________
De: Daniel Rodrigues <notifications@github.com>
Enviado: Wednesday, June 13, 2018 8:29:54 AM
Para: PHPJasper/phpjasper
Cc: hemimm; Mention
Assunto: Re: [PHPJasper/phpjasper] Support to Collections (#64)


Olá @hemimm<https://github.com/hemimm>, dê uma olhada no repositório de exemplos e estude um pouco mais de PHP, percebo que o problema não está na biblioteca.

Take a look at the examples repository and study a little more of PHP, I realize that the problem is not in the library

**Comment by hemimm** [comment]
Daniel

Complementando. O Mpdf basta instalar pelo Composer localmente. No servidor só é  transferido os pacotes locais. O Zint basta levar o seu executável no servidor. Os Relatórios  pdf gerado funcionará (com Mpdf e Zint) tanto localmente como no servidor. Para geração de Relatórios pdf utilizei PHP e CSS, além do Mpdf e Zint

Concordo que se o jrxml elaborado pelo Jaspersoft Studio, gerasse o pdf diretamente com o PHP e PHPJasper, seria mais prático e direto. Infelizmente não deu.

At. Mitugi

Enviado do Email<https://go.microsoft.com/fwlink/?LinkId=550986> para Windows 10

________________________________
De: Daniel Rodrigues <notifications@github.com>
Enviado: Wednesday, June 13, 2018 8:29:54 AM
Para: PHPJasper/phpjasper
Cc: hemimm; Mention
Assunto: Re: [PHPJasper/phpjasper] Support to Collections (#64)


Olá @hemimm<https://github.com/hemimm>, dê uma olhada no repositório de exemplos e estude um pouco mais de PHP, percebo que o problema não está na biblioteca.

Take a look at the examples repository and study a little more of PHP, I realize that the problem is not in the library
